---

- name: role git - push repository
  ansible.builtin.shell: |
    git branch -M {{ git_repo_branch }}
    git push -u {{ git_repo_path }} {{ git_repo_branch }}
  args:
    chdir: "{{ git_working_dir_path }}/{{ git_file_path }}"
  register: git_push_results
  run_once: yes

...
